version: '3.8'

services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - lakshya

  server:
    build: ./server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - lakshya

  admin:
    build: ./client/admin
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - lakshya

  coordinator:
    build: ./client/coordinator
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - server
    networks:
      - lakshya

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - admin
      - coordinator
    networks:
      - lakshya

volumes:
  mongo_data:

networks:
  lakshya:
    driver: bridge
